name: Integrity check

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pipenv
        pipenv install

    - name: Validate regular & extended decks
      run: |
        pipenv run build

    - name: Validate experimental deck
      run: |
        pipenv run build_experimental

    - name: Zip decks
      run: |
        ./zip_decks.sh
      id: zip-decks

    - name: Publish
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: ${{ steps.zip-decks.outputs.DECK_PATHS }}
        release: everfresh

      # TODO: Validate the csv file structure
